language: go
go:
- '1.12'
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure
deploy:
  provider: releases
  api_key:
    secure: Uis7GZfWaIkzMbYIKxAfoJEMs7EfJdVoCxK/sjPMiZWH3nEcKtNkmYPh5WfWHuJ//OMApZUMn+oVT5ORdLPRmbK0mWdlG6tO/LbbciJHVMBIqLlC4mETbAdq6GRL3McSorKI/97+dyxalkwHBJsjERZYA0j564Y1+J0Q6QhEgzmwimWWDBr548MgopWc7cZ6WCYZbw3Axd+E65ftjiGZZ1olLcteuBzRaA8mJgt7NJ3lnp94aC2YUHoXvFYfJFCrBa4HQL9zu2qBiwQWbFSDPN7dxMeIVPf5VW6R0NhQ04RMzv4pbDx+iShraXndMSP5MeH98ke2Q/ve3ig8CEldY94VjsG6KeHUkIhuB4IykGVe4XGTx7zamEeFm9NGZ7KwhK1SaS7qJCwvGOJ3M25jGmHNGJlEkxuppwKMdne6ogSVL2PcoE4yfAojP0cbxFnmQrHWe7HMfyMGh5vDls5rtydI8cQUA6rfIRTqaSPdErFw9uiCG/wdEP0xM4YMIft2FeFGGu4z2mGBsIYwuBloGJ9av3s+Ax6t7WEqT5N46eD3cymCotq0c05DGXrIZX6FM0BLgqpbIHaKpHJ9MiHggYzjojqdSNZ2IwAhhR2k0RC7FfANtq2bd94bpUm8wvrf8WEQOo4vDctnRrMJFFbNWtYuY3nyBUUxR8J5PjbR7gM=
  file:
    - terraform-provider-vcd_${TRAVIS_BRANCH}_macos.tar.gz
    - terraform-provider-vcd_${TRAVIS_BRANCH}_linux.tar.gz
    - terraform-provider-vcd_${TRAVIS_BRANCH}.exe
  skip_cleanup: true
  on:
    repo: rodion-goritskov/terraform-provider-vcd
    tags: true
